### ISSUE TITLE
FYI: Breaking change in Arduino_SNMP_Manager

### ISSUE THREAD

**Issue by shortbloke** [elegantalchemist/dekatron-speed#1]
Just to let you know if you update to the latest Arduino_SNMP_Manager library, there is a breaking change when callbacks are created or searched for. In that, you need to provide the IP address in addition to the OID. This was to allow the library to support querying the same OID from multiple devices.

In addition, I've updated the example to get the callback when creating the callback, rather than using findCallback. Either works, but it may simplify the code a little.

Original:
```
  // Create a handler for each of the OID
  snmp.addCounter32Handler(oidInOctets, &inOctets);
  snmp.addCounter32Handler(oidOutOctets, &outOctets);
  snmp.addTimestampHandler(oidUptime, &uptime);

  // Create the call back ID's for each OID
  callbackInOctets = snmp.findCallback(oidInOctets);
  callbackOutOctets = snmp.findCallback(oidOutOctets);
  callbackUptime = snmp.findCallback(oidUptime);
```

Revised for update Arduino_SNMP_Manager library:
```
  callbackInOctets  = snmp.addCounter32Handler(router, oidInOctets, &inOctets);
  callbackOutOctets  = snmp.addCounter32Handler(router, oidOutOctets, &outOctets);
  callbackUptime  = snmp.addTimestampHandler(router, oidUptime, &uptime);
```

Thanks Martin (shortbloke)

**Comment by elegantalchemist** [comment]
Thanks - I have updated the code using this.

Strangely enough, this bug also hit me even when I hadn't upgraded the SNMP manager library which is odd. Unless it auto-upgraded for me 'helpfully'.

Fixed now
